adding fav movie
FranktheTank123/UCB-MFE-python-preprogram pull request #26
Opened 2021-12-11 02:50 UTC by Moe-Saeed

2021-12-12 04:07 UTC, pusukuri requested changes
Indentation should be appropriate to be able to compile the code. Please fix it.

2021-12-12 04:07 UTC, pusukuri commented on Homeworks/HW1/mohammed_alshowaikhat/game_of_life.py
> +       cols=len(initial_state[0])
Space should be proper to be able to compile. Please fix it.

2021-12-12 20:33 UTC, Moe-Saeed commented on Homeworks/HW1/mohammed_alshowaikhat/game_of_life.py
> +       cols=len(initial_state[0])
Changes are made, now it should work, thanks for your feedback

2021-12-13 07:50 UTC, pusukuri approved these changes
Good work...

2021-12-13 07:50 UTC, merged